### ISSUE TITLE
Bluetooth Does not work

### ISSUE THREAD

**Issue by Arthur97172** [dragonflylee/Yoga-730-hackintosh#11]
just updated the clover today but after that, the Bluetooth does not work anymore, could you please check?

**Comment by dragonflylee** [comment]
@Arthur97172 
Refer https://github.com/acidanthera/BrcmPatchRAM
should use BrcmPatchRAM3.kext for 10.15
use BrcmPatchRAM2.kext for 10.14

 BrcmPatchRAM3.kext and  BrcmPatchRAM2.kext must not use together

**Comment by Arthur97172** [comment]
Thanks, I have fixed the Bluetooth issue

**Comment by Arthur97172** [comment]
This issue could close
