### ISSUE TITLE
键盘背光灯不亮

### ISSUE THREAD

**Issue by Arthur97172** [dragonflylee/Yoga-730-hackintosh#14]
我的系统是Catalina 10.15.3 , Clover 5103
现在键盘背光灯不亮,进入--系统偏好设置--键盘--更改键盘类型... 识别键盘的时候没有任何响应无法继续.

**Comment by dragonflylee** [comment]
Fn+空格键不管用吗

**Comment by Arthur97172** [comment]
重新装了一下系统好了.
