### ISSUE TITLE
Thunderbolt 3

### ISSUE THREAD

**Issue by tristan-k** [dragonflylee/Yoga-730-hackintosh#2]
Does connecting Thunderbolt 3 devices work? It isn't mentioned at all.

**Comment by dragonflylee** [comment]
I does not have any Thunderbolt 3 devices, can you test it?

**Comment by CantosSong** [comment]
@tristan-k It's working.

**Comment by tristan-k** [comment]
I can confirm that thunderbolt 3 devices are working, although without hotplug support. You'll have to restart the machine.
