### ISSUE TITLE
exact yoga 730-13lkb laptop but can't boot to Catalina latest update

### ISSUE THREAD

**Issue by u0xpsec** [dragonflylee/Yoga-730-hackintosh#29]
doesn't matter which branch I choose bcm/intel/oc I can't boot to installer. it always halts midway and reboots.
I haven't installed a different wifi card because I don't know yet if this will work.
the device has a Realtek wifi card and a 256gb nvme ssd. any help would be appreciated.
other than what's in the readme is there anything else that needs to be changed?

**Comment by dragonflylee** [comment]
try turn off wlan in BIOS maybe

**Comment by u0xpsec** [comment]
> try turn off wlan in BIOS maybe

That works, thanks. I didn’t think it would matter since there’s no drivers for it.
