### ISSUE TITLE
蓝牙只有在windows重启才可以使用，并且隔几秒一断，也是只能通过换网卡解决吗？

### ISSUE THREAD

**Issue by CantosSong** [dragonflylee/Yoga-730-hackintosh#3]
蓝牙只有在windows重启才可以使用，并且隔几秒一断，也是只能通过换网卡解决吗？

**Comment by CantosSong** [comment]
Type-C工作的很好，插拔都可以，Type-A不行

**Comment by dragonflylee** [comment]
蓝牙和无线网卡确实要换网卡了

**Comment by CantosSong** [comment]
- type-c  工作的完美可以热插拔   
- type-a 不能热插拔
- 蓝牙暂时不能连接
- 雷电口完美
- 外接显示器开机自带显示器不显示  需要盒盖之后再开启就可以了

**Comment by PowerDebugger** [comment]
@CantosSong 老铁显示器用的什么接口  什么转换器

**Comment by CantosSong** [comment]
@PowerDebugger 普通的typec转hdmi

**Comment by PowerDebugger** [comment]
@CantosSong 我的有时候合盖再开启也不行 有时候就死机了 需要重启 不过我是转了hdmi又转了个vga  打算买个typec转dp的测试一下  倒是我的type-a热插拔没问题  换了两个hub都没问题

**Comment by CantosSong** [comment]
@PowerDebugger 你的系统从哪里下载的，我从黑果小兵的下载的最新的

**Comment by PowerDebugger** [comment]
@CantosSong 文件名是这个 macOS High Sierra 10.13.6(17G65) Installer with Clover 4596 地址不清楚了 分享的百度网盘

**Comment by dragonflylee** [comment]
[macOS High Sierra 10.13.6](magnet:?xt=urn:btih:2758F09E08D2DFCB9A4E6B4EA5D5AA3BD7DB4416)
[macOS Mojave 10.14.5](magnet:?xt=urn:btih:4E3CB6E7E95550E441904D02BA65053078353928)
