### ISSUE TITLE
您好，请教您yoga13引导的问题

### ISSUE THREAD

**Issue by y655r** [dragonflylee/Yoga-730-hackintosh#33]
我想在yoga11s上装黑苹果，搜到了您两年前的yoga13的EFI，直接使用提示“smcReadKey received error 0x84 when reading key 'DLSM`”，进不了安装界面，是否因为您的config.plist里面缺少smbios的原因？应当选用哪个机型合适呢？打扰您了，谢谢。

**Comment by dragonflylee** [comment]
可以试试 Drop 掉 `DLSM` 这个表

```xml
<key>DropTables</key>
<array>
	<dict>
		<key>Signature</key>
		<string>DMAR</string>
	</dict>
	<dict>
		<key>Signature</key>
		<string>DLSM</string>
	</dict>
</array>
```
