### ISSUE TITLE
Bluetooth issues

### ISSUE THREAD

**Issue by ember3141** [dragonflylee/Yoga-730-hackintosh#35]
I have Ventura 13.6.3 running great, I got all the services working except for bluetooth. I had to use AirportItlwm instead of AirportBrcmFixup to get wifi working. I noticed in the repo's config.plist had the two BcrmBluetooth kexts listed, so I added BcrmPatchRAM3.kext and BrcmFirmwareData.kext to the kexts folder and to my config. Upon reboot, bluetooth still does not work. tried to check logs with grep, bcrm doesn't even appear. tried adding the other kexts the BrcmPatchRam readme instructs like bcrmbluetoothinjector and bcrmnonpatchram2 but nothing seems to work. I'm not familiar with the macOS kernel.

**Comment by dragonflylee** [comment]
try https://github.com/OpenIntelWireless/IntelBluetoothFirmware which support Intel Bluetooth

my yoga730 has replaced by DW1560/DW1820A,

**Comment by ember3141** [comment]
works great!
