### ISSUE TITLE
battery life in Lenovo Yoga 730

### ISSUE THREAD

**Issue by skandavc18** [dragonflylee/Yoga-730-hackintosh#4]
Wanted to know what is the battery life you are getting on your Hackintosh. 
I too have a Lenovo Yoga 730 with slightly different specs. I have an i5 and no dedicated Nvidia GPU. I used your clover folder. Except for poor Battery life, everything is working. I am getting around 3 hrs of battery life with moderate usage. Please help.

**Comment by yoshie902a** [comment]
3 hours seems low, do others have the same battery life?

**Comment by yoshie902a** [comment]
@skandavc18  Do you have a NVME drive? If so that might be your issue...

https://www.tonymacx86.com/threads/nvme-power-management-support-apst.273554/

**Comment by dragonflylee** [comment]
maybe https://github.com/acidanthera/CPUFriend can solve the power management problem

**Comment by skandavc18** [comment]
> @skandavc18 Do you have a NVME drive? If so that might be your issue...
> 
> https://www.tonymacx86.com/threads/nvme-power-management-support-apst.273554/

Yes. I have an NVME SSD. ( Samsung ). I will check out the link. Thanks

**Comment by skandavc18** [comment]
> maybe https://github.com/acidanthera/CPUFriend can solve the power management problem

Thanks. Will try it

**Comment by yoshie902a** [comment]
@dragonflylee I noticed the person that wrote CPUFriend also wrote, https://github.com/acidanthera/NVMeFix

This may be a solution.

**Comment by dragonflylee** [comment]
@yoshie902a  there has script to generate customized CPUFriendDataProvider.kext 
https://github.com/stevezhengshiqi/one-key-cpufriend

together with NVMeFix may solve the issue

**Comment by skandavc18** [comment]
> @yoshie902a there has script to generate customized CPUFriendDataProvider.kext
> https://github.com/stevezhengshiqi/one-key-cpufriend
> 
> together with NVMeFix may solve the
