### ISSUE TITLE
Can't Boot

### ISSUE THREAD

**Issue by Nininunz** [dragonflylee/Yoga-730-hackintosh#6]
Having trouble booting at all with this EFI. I can't even get to the installer, it just kernel panics. Installer contain macOS Mojave 10.14.6. It's been a while since I've done this but I couldn't get anything valuable from the kernel panic log.

**Comment by dragonflylee** [comment]
can you give any detail info? such as, hardware info

**Comment by Nininunz** [comment]
Yoga 730 13"
i5 8250U
UHD 620
8GB RAM
Stock 256GB Drive

**Comment by Nininunz** [comment]
I usually build the efi from scratch but I figured I would use this since it was done and I was in a rush. Was this efi built for different specs?

**Comment by Nininunz** [comment]
I don't really have time to do this so I was hoping I could use your efi. If not let me know and I'll make time to build one. Thx.

**Comment by dragonflylee** [comment]
still waiting for more info detail.

**Comment by dragonflylee** [comment]
Disable Security -> Intel SGX -> Intel SGX Controller
Disable Security -> Secure Boot
Switch RAID to AHCI in Configuration -> SATA Controller Mode

**Comment by Nininunz** [comment]
I did that. It ended up being voodooi2c and voodooi2chid. When I removed them the computer booted. Installer wouldn't load with them. Once I installed Mojave I put them back in clover and it boots now. Just can't get touchpad or touchscreen to work. I've rebuilt kextcache but nothing.

**Comment by Nininunz** [comment]
nvm its magically working now. weird.
