### ISSUE TITLE
F11 & F12 无法调节屏幕亮度了

### ISSUE THREAD

**Issue by Arthur97172** [dragonflylee/Yoga-730-hackintosh#8]
更新了最新的Clover后F11 & F12无法调节屏幕亮度了～～！现在只能进入‘系统偏好设置’今天亮度调节了。

**Comment by Arthur97172** [comment]
升级到10.15后无法使用，10.14是正常的。

**Comment by dragonflylee** [comment]
@Arthur97172 已修复
https://github.com/dragonflylee/Yoga-730-hackintosh/commit/d7bff5b096bcce5b9ebe12c1ef4c2975b00e2a13

**Comment by Arthur97172** [comment]
It's working now, you could close this issue.
