### ISSUE TITLE
Screen brightness

### ISSUE THREAD

**Issue by deadpixel134** [dragonflylee/Yoga-730-hackintosh#9]
The graphics memory is displayed correctly and adjusting brightness also works.
However, the maximum brightness is low.
It's almost 1/4 of maximum brightness.
Is there any way to adjust it?

**Comment by dragonflylee** [comment]
Is your Yoga730 is 13IKB with  i5-8250U? 
not 13IWL  with a i5-8265U

**Comment by deadpixel134** [comment]
okay thx. have a nice day
